version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "50051:50051"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
